# This is a basic workflow to help you get started with Actions

name: My-GitHub-Actions-Basics


on:
 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Hello Message in Testing
      run: echo "Hello World from Testing!"
    
    
  my_deploy:
    needs: [my_testing]
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Hello Message in Deploy
      run: echo "Hello World from deploy!"
    
