# This is a basic workflow to help you get started with Actions

name: My-GitHub-Actions-Basics
env:
 APPLICATION_NAME: "PHP Application"
 PACKAGE_NAME: "php app deploy ver ${{ github.sha }}"


on:
 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    env:
     VAR1: "This is Job Level Variable1"
     VAR2: "This is Job Level Variable2"
    
    steps:
    
    - name: Print Hello Message in Testing
      run: echo "Hello World from Testing!"
      
    - name: Execute few commands
      run: |
       echo "Hello Message1"
       echo "Hello Message2"
       echo "Application Name: ${{ env.APPLICATION_NAME }}"
       
    - name: Git clone repo
      uses: actions/checkout@v1
      
    - name: Print env vars
      run: |
       echo "Var 1 = ${{ env.VAR1 }}"
       echo "Var 1 = ${{ env.VAR2 }}"
       echo "Var 1 = $LOCAL_VAR"
      env:
       LOCAL_VAR: "This is Super Local Var"
       
    - name: List current folder
      run: ls -la
    
    
  my_deploy:
    needs: [my_testing]
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Hello Message in Deploy
      run: echo "Hello World from deploy!"
      
    - name: Deployment package
      run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
      
    - name: Test some packages presence
      run:  aws --version
    
